sudo: false

language: node_js

node_js:
  - 10.14.2

install:
  - npm install

before_script:
  - curl https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
  - echo "deb https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.4 multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -y install mongodb-org
  - sudo systemctl start mongod

addons:
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /

services:
  - docker
  - mongodb 

script:
  - npm run lint
  - npm test
  - ./artifact.sh
